# Generated by Django 3.0.3 on 2020-05-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2020)),
                ('attain', models.BooleanField()),
            ],
            options={
                'verbose_name': 'bucketList',
                'verbose_name_plural': 'bucketLists',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FactItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'factItem',
                'verbose_name_plural': 'factItems',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.TextField(blank=True)),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'mailBox',
                'verbose_name_plural': 'mailBoxes',
                'ordering': ('ip',),
            },
        ),
        migrations.CreateModel(
            name='MapBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(default=1991)),
                ('image', models.ImageField(blank=True, upload_to='mapBadge')),
            ],
            options={
                'verbose_name': 'mapBadge',
                'verbose_name_plural': 'mapBadges',
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='PfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfilter', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='pfItem')),
                ('year', models.IntegerField(default=2020)),
                ('month', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'pfItem',
                'verbose_name_plural': 'pfItems',
                'ordering': ('dfilter', 'year', 'month'),
            },
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scale', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'verbose_name': 'skillList',
                'verbose_name_plural': 'skillLists',
                'ordering': ('name',),
            },
        ),
    ]
